name: Build Application CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build Node.js Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del Código Fuente
        uses: actions/checkout@v3

      - name: Configurar Entorno Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cachear Dependencias de Node.js
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
        
      - name: Instalar Dependencias del Proyecto

        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install

      - name: Instalar esbuild Globalmente

        run: npm install -g esbuild

      - name: Compilar la Aplicación NestJS
        run: npm run build

      - name: Configurar Docker Buildx

        uses: docker/setup-buildx-action@v2

      - name: Construir Imagen Docker

        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile 

          load: true